name: deploy to ec2
on:
 workflow_run:
     workflows: ["Docker Image CI"]
     types : 
             - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: deploy to ec2
            uses: appleboy/ssh-action@master
            with:
                host: ${{secrets.EC2_HOST}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_KEY}}
                script: | 
                   docker pull sakshik007/node-app:latest
                   docker rm -f node-app || true
                   docker run -d -p 4000:3000 --name node-app sakshik007/node-app:latest
                
                    

                 